spring.application.name=demo
server.port=9090
logging.file.name=magicSystem.log
#（時間 - 等級 - 訊息）
logging.pattern.file=%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n
logging.logback.rollingpolicy.max-file-size=10MB
logging.logback.rollingpolicy.max-history=7

important=${IMPORTANT:50}
normal=${NORMAL:100}
urgent=${URGENT:10}